name: Build All
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  IMAGE_URL: "ghcr.io/${{ github.repository_owner }}/robomaster"
  RUN_ARGS: "-t --rm --uidmap 1000:0:1 -v .:/code -w /code/ut-robomaster $IMAGE_URL"
jobs:
  build:
    strategy:
        matrix:
          robot: [standard, hero, sentry]
        fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build code
      run: podman run ${{ env.RUN_ARGS }} scons build robot=${{ matrix.robot }}
      
