name: Try building for each robot

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: gacts/install-podman@v1.1.0
    - run: alias docker=podman
    - uses: whoan/docker-build-with-cache-action@v8.0.2
      with:
        push_image_and_stages: false
        image_tag: "ut-robomaster"
    # - name: Build the container
      # run: podman build --tag ut-robomaster .
    - name: Run the container
      run: podman run -dt --rm --userns keep-id:uid=1000,gid=1000 -v .:/code -w /code/ut-robomaster ut-robomaster
    - name: Build Standard
      run: podman exec -l scons build robot=standard
    - name: Build Hero
      run: podman exec -l scons build robot=hero
    - name: Build Sentry
      run: podman exec -l scons build robot=sentry
      
