name: Test building for each robot
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  RUN_ARGS: "-t --rm --userns keep-id:uid=1000,gid=1000 -v .:/code -w /code/ut-robomaster"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Podman
      uses: gacts/install-podman@v1.1.0
    - name: Pull container
      run: podman pull ghcr.io/${{ github.repository_owner }}/robomaster
    - name: Build Standard
      run: podman run ${{ env.RUN_ARGS }} container scons build robot=standard
    - name: Build Hero
      run: podman run ${{ env.RUN_ARGS }} container scons build robot=hero
    - name: Build Sentry
      run: podman run ${{ env.RUN_ARGS }} container scons build robot=sentry
      
