name: Try building for each robot

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the container
      run: docker build --tag ut-robomaster --file Containerfile .
    - name: Run the container
      run: docker run -dt --rm --user dev:dev --name me -v .:/code -w /code/ut-robomaster ut-robomaster
    # - run: echo $(pwd)
    - run: docker exec me ls -la
    - run: docker --version
    - name: Build Standard
      run: docker exec me scons build robot=standard
      
