name: Build All
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  IMAGE_URL: "ghcr.io/${{ github.repository_owner }}/robomaster"
  RUN_ARGS: "-t --rm --userns keep-id:uid=1000,gid=1000 -v .:/code -w /code/ut-robomaster ${{ env.IMAGE_URL }}"
jobs:
  build:
    strategy:
        matrix:
          robot: [standard, hero, sentry]
        fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Install Podman
      uses: gacts/install-podman@v1.1.0
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build code
      run: podman run ${{ env.RUN_ARGS }} scons build robot=${{ matrix.robot }}
      
