name: Try building for each robot

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    # - name: Build the container
    #   run: podman build --tag "ut-robomaster" .
    # - name: Run the container
    #   run: podman run -dt --rm --userns keep-id:uid=1000,gid=1000 -v .:/code -w /code/ut-robomaster ut-robomaster
    # - run: echo $(pwd)
    # - run: podman exec -l ls -la
    - run: podman --version
    # - name: Build Standard
      # run: podman exec -l scons build robot=standard
      
