name: Test building for each robot
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  RUN_ARGS: "-t --rm --userns keep-id:uid=1000,gid=1000 -v .:/code -w /code/ut-robomaster"
jobs:
  build:
    strategy:
        matrix:
          robots: [standard, hero, sentry]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Podman
      uses: gacts/install-podman@v1.1.0
    - name: Pull container
      run: podman pull ghcr.io/${{ github.repository_owner }}/robomaster
    - name: Build code
      run: podman run ${{ env.RUN_ARGS }} robomaster:latest scons build robot=$
      
