name: Lint C++ files

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: '-*'
          files-changed-only: false
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
